### ISSUE TITLE
Spaces in a filepath cause it to fail

### ISSUE THREAD

**Issue by smartycope** [p-ranav/argparse#111]
ArgumentParser treats "path/to/the file" and path/to/the\ file as separate positional arguments.

**Comment by skrobinson** [comment]
Can you provide more details?  I am unable to reproduce in a unit test.

**Comment by smartycope** [comment]
Yes, sorry. I'm writing a program that takes in a file path as the first (and only) positional parameter. When I put in a file path that had spaces, whether enclosed in parentheses or using backslashes, it would give me an error saying "too many positional arguments" (or something close to that). I took that to mean it was still delimiting the spaces in the file path, as I couldn't find anywhere else in my code that would cause that problem. It works fine with paths without spaces, for example. 

Aug 16, 2021 2:06:45 PM skrobinson ***@***.***>:

**Comment by skrobinson** [comment]
I suspect your shell is parsing/splitting the string before `::parse_args(int argc, const char *const argv[])` sees it.  Could you inspect the value of `argc` sent to `::parse_args` either with a debugger or by printing its value?  With the configuration you describe and escaped (or quoted) spaces, I expect the value of `argc` to be 2.

**Comment by GDelevoye** [comment]
I think it is not just spaces

I tried this :

```C++
    parser.add_argument("--self_path")
            .help("Path to this executable. <DEFAULT : Current directory>")
            .default_value(boost::filesystem::current_path());
```

It worked right with the [conan center 2.1 version](https://conan.io/center/argparse) but after using the headers from the repo directly, I got segmentation faults

Ubuntu LTS 20.04 using cmake3.5.2 std_20

**Comment by GDelevoye** [comment]
In my case I found this workaround : 

Pass my default argument as a regular string, with a .string(): 

```C++
    parser.add_argument("--self_path")
            .help("Path to this executable. <DEFAULT : Current directory>")
            .default_value(boost::filesystem::current_path().string());
```

Then transform it into a filepath : 

```C++
    auto self_path = parser.get<std::string>("--self_path");
    spdlog::debug((boost::format("Received path = %1%") % self_path).str());
```

**Comment by skrobinson** [comment]
I think you have found a separate issue from @smartycope. The original #111 did not involve a segfault, just an incorrect number of parsed arguments.

I'm glad you found a solution. This may become a problem that others find as well and want to use your answer. Could you open a new issue, with a title mentioning boost::filesystem:current_path and segmentation fault?

Either leave the new issue open and see if anyone responds. Or answer your own issue and close it. I think this will give better visibility to the issue so that a fix can be found and applied to `argparse`. Or you may solve someone else's issue for them with your workaround.

**Comment by smartycope** [comment]
You were right, the shell was splitting the arguments before it reached the program.  The problem was on my end. Thanks for the help!
