### ISSUE TITLE
Add ability to check if `ArgumentParser` parsed any input

### ISSUE THREAD

**Issue by bwpge** [p-ranav/argparse#212]
**_EDIT: see the discussion below for more information on how this issue evolved_**

First I want to say thank you so much for the excellent work done on this library! I was hoping I could request a feature regarding subcommands.

I am building out a utility that requires the user to primarily use a subcommand to trigger any useful behavior. Essentially the desired behavior is:

- Setup parser with subcommands
- Parse arguments
- Check if any subcommand has been used
    - If yes, do subcommand stuff
    - If no, print help message and exit with error code

This would be similar behavior as running `git` with no subcommands.

I was looking through the header, and it appears the way to do this is use the member function `ArgumentParser::is_subcommand_used`. To achieve the above described effect, I would need to loop over a list of hard-coded commands from a separate list. This isn't the end of the world of course, since it's pretty simple to keep a list of the commands that have been implemented.

However, it would be nice to be able to do something like:

```cpp
// setup "program" with subcommands and parse_args
// ...

if (!program.has_used_subcommands())
{
    std::cerr << program;
    std::exit(1);
}
```

A potential implementation could just be a wrapper function around `m_subparser_used` (not sure how correct this is, not tested):

```cpp
auto has_used_subcommands()
{
    return std::any_of(m_subparser_used.begin(), m_subparser_used.end(),
        [](const auto& it){ return it.second; });
}
```

Although, this does present an ancillary consideration of checking *which* subcommand was used. So perhaps it would be better to return a `std::optional` reference from `m_subparsers` to the subcommand, and just return `std::nullopt` if none were used (which would allow the same conditional check described above).

**Edit:** fixed a typo
**Edit 2:** fixed error with lamda

**Comment by cygnoros** [comment]
Great point, I do like the ergonomics of a simple `if (!program) { /* exit */ }` :)

For my specific use case I think this would be just fine, since my base parser does not have any flags or switches that result in any further business logic (and I believe the default implementation for `-v` and `-h` always results in an exit).

I *could* foresee someone's use case where the base command has some global option that applies to all subcommands (for example, `git -C some/path` or `git -c foo.bar=baz`) which would still require a subsequent subcommand to be used for any meaningful business logic. However, now `program` in this case would evaluate to `true` since it parsed some information.

In this scenario, the above solution would not be adequate since they will still have to check if each subparser was used and `ArgumentParser` does not provide public access to its subparser objects. So they would have to fallback to iterating through a hardcoded list of subcommands and checking `is_subcommand_used`.

I'm not sure how much of a corner case that is, but it seems like a reasonable enough usage.

**Comment by skrobinson** [comment]
Because all parsers have the same API, it would be possible to test individual subcommands. With an "add_command" subparser, `if (add_command) {}` would behave similar to `if (program) {}`.

> ...ArgumentParser does not provide public access to its subparser objects.

True. But the subparser instances must be constructed before adding to the base parser and can be stored in a `std::map<std::string_view, argparse::ArgumentParser>` so there is associative and iterable access to all parsers.

Or maybe we could provide const access to the internal list of subparsers after parsing. Hmm... Interesting... Subparsers are a very new feature and I imagine some things are yet to be settled.

**Comment by bwpge** [comment]
> Because all parsers have the same API, it would be possible to test individual subcommands. With an "add_command" subparser, `if (add_command) {}` would behave similar to `if (program) {}`.

Understood, totally agreed this would be a solid feature.

Taking a step back and looking at some of my previous projects that utilized Python's argparse module, the way I actually did this was with: `subparser = program.add_subparser(dest='subcommand', required=True, ...)`. This leveraged the destination variable name as a way to enforce the user to use a subcommand -- with `required=True`, the parser would fail if no subcommand was provided (and thus trigger help message/exit behavior). I'm not sure this library would want to try and emulate that sort of behavior though, since we don't have the same facilities as Python (e.g.,  `__setattr__` tricks and such).

That being said, I think your idea of providing `const` access to the subparsers is the best way to enable some extended logic without too much hassle to implement.

Just from a tracking perspective, it seems there are two separate issues fleshing out in our discussion so we may want to split off one or the other to a new issue (and maybe rename this one):

- Provide some implementation (`operator bool`, whatever) that checks if the parser actually parsed anything
- Provide `const` access to subparsers (whether through directly exposing the member map/list, or through some kind of getter that provides validation logic or something)

**Comment by skrobinson** [comment]
> I'm not sure this library would want to try and emulate that sort of behavior though, since we don't have the same facilities as Python (e.g., `__setattr__` tricks and such).

It's not so much about introspection as where to do the check. This is something that someone might want to implement in the future.

> ...it seems there are two separate issues...

I've begun trying out a few ways to implement `ArgumentParser::operator bool`.

ArgumentParser-based access to subparsers is an orthogonal feature and I agree it would work better as a separate Issue.

**Comment by bwpge** [comment]
In line with the above, I have edited the title to more accurately reflect what this issue is tracking and made a note in the issue body.

I will open a separate issue to track discussion on subparser access.

**Comment by bwpge** [comment]
Really appreciate the quick work on this feature request, cheers :)
