### ISSUE TITLE
A "hide_from_help" flag for add_subparser

### ISSUE THREAD

**Issue by heshiming** [p-ranav/argparse#258]
Hi,

I'm wondering if you can consider adding this "hide_from_help" flag to the `add_subparser` call. I've got the implementation here: https://github.com/heshiming/argparse/commit/f69b50bf4af6eb7e34aa3ec265d47f3f3331e048 .

Basically, I would like to have certain sensitive commands to be excluded from the help message but still let argparse to parse it. The implementation is against subparser only, not arguments.

**Comment by skrobinson** [comment]
Thank you for this. I would support this addition with a few changes.

`m_hide_from_help` -> `m_suppress`

`ArgumentParser::set_hide_from_help` -> `ArgumentParser::set_suppress`

My preference for "suppress" is because that is the terminology used in Python argparse and the concept will be familiar to users.

Does this need to be part of `add_subparser`? Or could it be part of parser creation before it is added as a subparser?

Example:

```cpp
argparse::ArgumentParser hidden_cmd("hidden");
hidden_cmd.set_suppress(true);
hidden_cmd.add_argument("files").remaining();
program.add_subparser(hidden_cmd);
```

This should also include `m_suppress` in ArgumentParser copy ctor. Please also add tests and update the README.

**Comment by a-is** [comment]
Several months have passed since the last (and only) @heshming message and I decided to implement this functionality. My code is based on the proposed @heshming implementation and taking into account the comments of @skrobinson.

I have pushed the same comment to my repository several times, because when creating the original commit, my text editor deleted all trailing whitespaces and I tried to bring them back.
