### ISSUE TITLE
Can the code parse arguments in format -key="some value with spaces"

### ISSUE THREAD

**Issue by nikitin-** [p-ranav/argparse#338]
Hello! 

Is it possible to setup the code of the parser to parse aguments in this format
-key="some value with spaces"

e.g. 
'-key' is a parameter name
'=' is a delimiter 
"some value with spaces" is a value (surrounded by doublequotes)

Thank you in advance

**Comment by p-ranav** [comment]
This almost works with `program.set_prefix_chars` and `program.set_assign_chars`. 

I say almost because, for some reason in the past, argparse prefix chars [was decided to be 2 characters long](https://github.com/p-ranav/argparse/blob/master/include/argparse/argparse.hpp#L2227). I'll have to revisit that decision. But if you design it as a 2-character "long prefix", e.g., `-D`, it works. 

```console
foo:bar $ ./main -Dkey="some string with spaces"
Key: some string with spaces
```

```cpp
#include "argparse.hpp"
#include <iostream>

std::string argname{"-Dkey"};

int main(int argc, char* argv[]) {

  argparse::ArgumentParser program("test");

  program.set_prefix_chars("-D");
  program.set_assign_chars("=");

  program.add_argument(argname);

  try {
    program.parse_args(argc, argv);
  }
  catch (const std::exception& err) {
    std::cerr << err.what() << std::endl;
    std::cerr << program;
    return 1;
  }

  if (program.is_used(argname)) {
    std::cout << "Key: " << program.get(argname) << std::endl;
  }
  
}
```

**Comment by p-ranav** [comment]
Okay! Sounds good! Closing this.
