### ISSUE TITLE
Can you create releases?

### ISSUE THREAD

**Issue by marcovc** [p-ranav/argparse#91]
I'm trying to use this library through hunter package management system. Would you mind creating some releases once in a while to make it easier to track?

thanks!
Marco

**Comment by p-ranav** [comment]
Sure, will do!

**Comment by xBeAsTx** [comment]
4 month later... still no release...
Moreover, no any releases since 2019 year

**Comment by Wuestenschiff** [comment]
:( Tried to figure out why my code was not working using the `ArgumentParsert.present` feature. Than I realized this was merged since 2 years but the release is even older. Looks like I need to look for another parser as we need to fetch our dependencies via a dependency tool. So using master is not an option. Shame really liked what I have seen so far.

**Comment by p-ranav** [comment]
Created the release [here](https://github.com/p-ranav/argparse/releases/tag/v2.1). Sorry about the delay and lack of activity here, will do better from now.
