### ISSUE TITLE
how to use: auto str_arg = args.get<std::string>(...) 

### ISSUE THREAD

**Issue by steven-varga** [p-ranav/argparse#96]
Love your work! 
I am experiencing difficulty with parsing the following:
```
auto topic = arg.get<std::string>("--topic");
```
This one works fine:
```
auto topic = arg.get<const char*>("--topic");
```
I wonder what I am doing wrong?

Also I tried to find the version in the header file, but didn't find any macro as you are in favour of `#pragma once`, would it be possible something similar to:
```
#define ARGPARSE_VERSION_INFO major.minor[.build[.revision]] 
```

**Comment by p-ranav** [comment]
This is likely due to type deduction mismatch. 

I am going to assume you created the argument like so:

```cpp
program.add_argument("--topic")
  .default_value("some default value");
```

Here, C++ deduces the default value (and therefore the type of the argument) as `const char *`

To be clear about the type of the argument (to use `std::string`), use:

```cpp
program.add_argument("--topic")
  .default_value(std::string{"some default value"});
```

If you didn't do the above, then the compiler (and therefore argparse) think that the type of the argument `--topic` is `const char *`

Thus, the `any_cast` to `std::string` fails.

**Comment by steven-varga** [comment]
Thanks a lot! `std::string{"literal"}` did the job...
